package com.example.lambda.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * API Gateway REST (v1) Lambda Authorizer response model + builder.
 *
 * "Deny by default, except ...":
 *  - If you add allowed method ARNs => emits a single Allow statement for those ARNs.
 *  - If you add nothing => emits an explicit Deny "*" (safe because no allows exist).
 *
 * No wildcards are generated by this builder. You must pass explicit method ARNs.
 */
public record RestApiGwAuthorizerResponse(
    String principalId,
    PolicyDocument policyDocument
) {

    public static final String POLICY_VERSION = "2012-10-17";
    public static final String INVOKE_ACTION = "execute-api:Invoke";
    public static final String EFFECT_ALLOW = "Allow";
    public static final String EFFECT_DENY = "Deny";

    public record PolicyDocument(
        String Version,
        List<Statement> Statement
    ) {}

    public record Statement(
        String Action,
        String Effect,
        List<String> Resource
    ) {}

    public static Builder builder(final String principalId) {
        return new Builder(principalId);
    }

    public static final class Builder {

        private final String principalId;
        private final List<String> allowedMethodArns = new ArrayList<>();

        private Builder(final String principalId) {
            if (principalId == null || principalId.isBlank()) {
                throw new IllegalArgumentException("principalId must not be blank");
            }
            this.principalId = principalId;
        }

        /**
         * Allow an API Gateway method ARN.
         * Example:
         * arn:aws:execute-api:eu-central-1:123456789012:apiId/prod/GET/orders
         */
        public Builder allowMethodArn(final String methodArn) {
            if (methodArn == null || methodArn.isBlank()) {
                throw new IllegalArgumentException("methodArn must not be blank");
            }
            allowedMethodArns.add(methodArn);
            return this;
        }

        /**
         * Build the response.
         *
         * - If at least one allow exists: emits an Allow statement for those exact ARNs.
         * - If none: emits an explicit Deny "*" (safe because there are no allows).
         */
        public RestApiGwAuthorizerResponse build() {
            final List<Statement> statements;

            if (!allowedMethodArns.isEmpty()) {
                statements = List.of(
                    new Statement(
                        INVOKE_ACTION,
                        EFFECT_ALLOW,
                        List.copyOf(allowedMethodArns)
                    )
                );
            } else {
                statements = List.of(
                    new Statement(
                        INVOKE_ACTION,
                        EFFECT_DENY,
                        Collections.singletonList("*")
                    )
                );
            }

            return new RestApiGwAuthorizerResponse(
                principalId,
                new PolicyDocument(POLICY_VERSION, statements)
            );
        }
    }
}
